### ISSUE TITLE
Create Team Work contract

### ISSUE THREAD

**Issue by manvirsingh96** [UBC-MDS/OlymPulse#2]

**Comment by AguilarRaul** [comment]
It seems like this time the team contract need be located in the root directory 
<img width="756" alt="image" src="https://user-images.githubusercontent.com/93731101/219551717-7154c4f8-1740-4c7f-b6f4-f8c0b600401d.png">

**Comment by manvirsingh96** [comment]
hmm should I move it there then?

**Comment by manvirsingh96** [comment]
PR link to upload team contract to the repo https://github.com/UBC-MDS/OlymPulse/pull/8

**Comment by AguilarRaul** [comment]
#12
